spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: jdbc:mysql://${DB_ADDRESS}:${DB_PORT}/mentomen?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: ${DB_USER}
    password: ${DB_PW}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    static-path-pattern: /static/**

logging:
  file:
    path: ${FILE_PATH}
    max-size: 500MB
    max-history: 30
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
    com.amazonaws.util.EC2MetadataUtils: error

server:
  servlet:
    encoding.force-response: true

cloud:
  aws:
    credentials:
      accessKey: ${AWS_ACCESS_KEY_ID}
      secretKey: ${AWS_SECRET_ACCESS_KEY}
    s3:
      bucket: ${BUCKET_NAME}
    region:
      static: ap-northeast-2
    stack:
      auto: false

product:
  client-id: ${CLIENT_ID}
  client-secret: ${CLIENT_SECRET}
  dauth: ${DAUTH_B1ND}
  open-dodam: ${OPEN_DODAM_B1ND}
  jwt-secret-key: ${JWT_SECRET_KEY}

